baseURL = 'giaoooooo.github.io'
languageCode = 'en-us'
title = "No Time to Die"
theme = 'paper'

[params]
    avator = 'https://2.gravatar.com/avatar/7c9ef9ed9487c38e2db7750cc76d8e32?size=256'
    name = '007 Lin'
    bio = "007 doesn't mean 7*24"