baseURL = 'giaoooooo.github.io'
languageCode = 'en-us'
title = "No Time to Die"
theme = 'paper'

[params]
    avator = 'https://freepngimg.com/save/166160-craig-daniel-free-hq-image/709x800'
    name = '007 Lin'
    bio = "007 doesn't mean 7*24"